name: Typescript Package CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  typescript:
    uses: skyleague/node-standards/.github/workflows/reusable-typescript.yml@main
    with:
      working-directory: ./scripts
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
